/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pengiriman_barang;

/**
 *
 * @author Tasya
 */
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksidb;
import java.sql.*;

public class barang extends javax.swing.JFrame {
    private Connection conn;
    private DefaultTableModel tableModel;
    public Statement st;
    public ResultSet rs;
    /**
     * Creates new form barang
     */
    public barang() {
        initComponents();
        conn = koneksidb.BukaKoneksi();
        tableModel = (DefaultTableModel) tablebarang.getModel();
        TampilData();
        
        // Tambahkan MouseListener ke tabel
        tablebarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tablebarang.getSelectedRow();
                if(row != -1) {
                    kolom1.setText(tableModel.getValueAt(row, 0).toString());
                    kolom2.setText(tableModel.getValueAt(row, 1).toString());
                    kolom3.setText(tableModel.getValueAt(row, 2).toString());
                    kolom4.setText(tableModel.getValueAt(row, 3).toString());
                    kolom5.setText(tableModel.getValueAt(row, 4).toString());
                }
            }
        });
    }
    private void TampilData(){
        try{
            st = conn.createStatement();
            rs = st.executeQuery("SELECT*FROM barang");
            
            tableModel.setRowCount(0); // Clear the table model
            
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("Kode");
            model.addColumn("Barang");
            model.addColumn("Jenis");
            model.addColumn("Jumlah");
            model.addColumn("Harga");
            int no= 1;
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            model.setRowCount(0);
            
            while(rs.next()){
                Object[] data={
                rs.getString("Kode_barang"),
                rs.getString("Nama_barang"),
                rs.getString("Jenis_barang"),
                rs.getInt("Jumlah_barang"),
                rs.getInt("Harga_barang"),
                };
            model.addRow(data);
            tablebarang.setModel(model);
            tableModel.addRow(data);
            }
        }catch(Exception e){
            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buatbtn = new javax.swing.JButton();
        caribtn = new javax.swing.JButton();
        pbhrbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kolom1 = new javax.swing.JTextField();
        kolom2 = new javax.swing.JTextField();
        kolom3 = new javax.swing.JTextField();
        kolom4 = new javax.swing.JTextField();
        kolom5 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablebarang = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        pcrbox = new javax.swing.JComboBox<>();
        pencarian = new javax.swing.JTextField();
        kembalibtn = new javax.swing.JButton();
        ulangbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        buatbtn.setText("Buat");
        buatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatbtnActionPerformed(evt);
            }
        });

        caribtn.setText("Cari");
        caribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribtnActionPerformed(evt);
            }
        });

        pbhrbtn.setText("Perbaharui");
        pbhrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbhrbtnActionPerformed(evt);
            }
        });

        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Kode barang");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nama barang");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Jenis barang");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah barang");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Harga barang");

        kolom1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolom1ActionPerformed(evt);
            }
        });

        kolom5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kolom5ActionPerformed(evt);
            }
        });

        tablebarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode", "Barang", "Jenis", "Jumlah", "Harga"
            }
        ));
        jScrollPane3.setViewportView(tablebarang);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setText("FORM BARANG");

        pcrbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode", "Barang", "Jenis", "Jumlah", "Harga" }));
        pcrbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcrboxActionPerformed(evt);
            }
        });

        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        kembalibtn.setText("Kembali");
        kembalibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalibtnActionPerformed(evt);
            }
        });

        ulangbtn.setText("Ulang");
        ulangbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kembalibtn)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kolom2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kolom1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kolom3, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kolom4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kolom5, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(caribtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(pcrbox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(buatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(pbhrbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hapusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(ulangbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(kolom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(kolom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kolom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(kolom4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(kolom5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buatbtn)
                    .addComponent(pbhrbtn)
                    .addComponent(hapusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ulangbtn))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caribtn)
                    .addComponent(pcrbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(kembalibtn)
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_262293274_BgGtnhf3gAZJkEt5vMj88oUK5Pwjguji.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kolom5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolom5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolom5ActionPerformed

    private void pbhrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbhrbtnActionPerformed
        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Failed to connect to database!");
            return;
        }

        int row = tablebarang.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan diperbarui!");
            return;
        }

        try {
            String kode = kolom1.getText();
            String nama = kolom2.getText();
            String jenis = kolom3.getText();
            int jumlah = Integer.parseInt(kolom4.getText());
            int harga = Integer.parseInt(kolom5.getText());

            String query = "UPDATE barang SET Nama_barang = ?, Jenis_barang = ?, Jumlah_barang = ?, Harga_barang = ? WHERE Kode_barang = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, nama);
            pstmt.setString(2, jenis);
            pstmt.setInt(3, jumlah);
            pstmt.setInt(4, harga);
            pstmt.setString(5, kode);
            pstmt.executeUpdate();

            TampilData(); // Refresh tabel setelah update

            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Jumlah dan Harga harus berupa angka!");
        }
    }//GEN-LAST:event_pbhrbtnActionPerformed

    private void pcrboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcrboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcrboxActionPerformed

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianActionPerformed

    private void kembalibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalibtnActionPerformed
        halaman_utama halaman_utamaForm = new halaman_utama();
        halaman_utamaForm.setVisible(true);
        this.dispose(); // close the current form
    }//GEN-LAST:event_kembalibtnActionPerformed

    private void kolom1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kolom1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kolom1ActionPerformed

    private void buatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatbtnActionPerformed
        if (conn == null) {
        JOptionPane.showMessageDialog(null, "Failed to connect to database!");
        return;
    }

    try {
        String kode = kolom1.getText();
        String nama = kolom2.getText();
        String jenis = kolom3.getText();
        int jumlah = Integer.parseInt(kolom4.getText());
        int harga = Integer.parseInt(kolom5.getText());

        String query = "INSERT INTO barang (Kode_barang, Nama_barang, Jenis_barang, Jumlah_barang, Harga_barang) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, kode);
        pstmt.setString(2, nama);
        pstmt.setString(3, jenis);
        pstmt.setInt(4, jumlah);
        pstmt.setInt(5, harga);
        pstmt.executeUpdate();

        // Add the new data to the table model
        tableModel.addRow(new Object[]{kode, nama, jenis, jumlah, harga});
        
        TampilData();

        // Clear the input fields
        kolom1.setText("");
        kolom2.setText("");
        kolom3.setText("");
        kolom4.setText("");
        kolom5.setText("");

        JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Jumlah dan Harga harus berupa angka!");
    }
    }//GEN-LAST:event_buatbtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
    if (conn == null) {
        JOptionPane.showMessageDialog(null, "Failed to connect to database!");
        return;
    }

    int row = tablebarang.getSelectedRow();
    if (row == -1) {
        JOptionPane.showMessageDialog(null, "Select a row to delete!");
        return;
    }

    String kode = (String) tablebarang.getValueAt(row, 0);
    String nama = (String) tablebarang.getValueAt(row, 1);
    String jenis = (String) tablebarang.getValueAt(row, 2);
    int jumlah = (int) tablebarang.getValueAt(row, 3);
    int harga = (int) tablebarang.getValueAt(row, 4);

    try {
        String query = "DELETE FROM barang WHERE Kode_barang = ? AND Nama_barang = ? AND Jenis_barang = ? AND Jumlah_barang = ? AND Harga_barang = ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, kode);
        pstmt.setString(2, nama);
        pstmt.setString(3, jenis);
        pstmt.setInt(4, jumlah);
        pstmt.setInt(5, harga);
        pstmt.executeUpdate();

        tableModel.removeRow(row);

        TampilData(); // Call TampilData() to refresh the table

        JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void caribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribtnActionPerformed
        if (conn == null) {
        JOptionPane.showMessageDialog(null, "Failed to connect to database!");
        return;
    }

    String selectedOption = (String) pcrbox.getSelectedItem();
    String searchValue = pencarian.getText();

    String columnName = "";
    switch (selectedOption) {
        case "Kode":
            columnName = "Kode_barang";
            break;
        case "Barang":
            columnName = "Nama_barang";
            break;
        case "Jenis":
            columnName = "Jenis_barang";
            break;
        case "Jumlah":
            columnName = "Jumlah_barang";
            break;
        case "Harga":
            columnName = "Harga_barang";
            break;
        default:
            JOptionPane.showMessageDialog(null, "Invalid option selected!");
            return;
    }

    try {
    String query = "SELECT * FROM barang WHERE " + columnName + " LIKE?";
    PreparedStatement pstmt = conn.prepareStatement(query);
    pstmt.setString(1, "%" + searchValue + "%");
    ResultSet rs = pstmt.executeQuery();

    tableModel.setRowCount(0); // Clear the table model

    if (rs.next()) { // Check if rs has any rows
        do {
            Object[] data = {
                rs.getString("Kode_barang"),
                rs.getString("Nama_barang"),
                rs.getString("Jenis_barang"),
                rs.getInt("Jumlah_barang"),
                rs.getInt("Harga_barang")
            };
            tableModel.addRow(data);
        } while (rs.next()); // Use do-while loop to iterate over rs

        tablebarang.setModel(tableModel);

        JOptionPane.showMessageDialog(null, "Data berhasil dicari!");
    } else {
        JOptionPane.showMessageDialog(null, "Data tidak bisa dicari!");
    }
} catch (SQLException e) {
    JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
}

    }//GEN-LAST:event_caribtnActionPerformed

    private void ulangbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangbtnActionPerformed
        kolom1.setText("");
        kolom2.setText("");
        kolom3.setText("");
        kolom4.setText("");
        kolom5.setText("");
    }//GEN-LAST:event_ulangbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatbtn;
    private javax.swing.JButton caribtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembalibtn;
    private javax.swing.JTextField kolom1;
    private javax.swing.JTextField kolom2;
    private javax.swing.JTextField kolom3;
    private javax.swing.JTextField kolom4;
    private javax.swing.JTextField kolom5;
    private javax.swing.JButton pbhrbtn;
    private javax.swing.JComboBox<String> pcrbox;
    private javax.swing.JTextField pencarian;
    private javax.swing.JTable tablebarang;
    private javax.swing.JButton ulangbtn;
    // End of variables declaration//GEN-END:variables
}
