/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pengiriman_barang;

/**
 *
 * @author Tasya
 */
public class halaman_utama extends javax.swing.JFrame {

    /**
     * Creates new form form
     */
    public halaman_utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pengirimanbtn = new javax.swing.JButton();
        pelangganbtn = new javax.swing.JButton();
        kurirbtn = new javax.swing.JButton();
        barangbtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pengirimanbtn.setText("Pengiriman");
        pengirimanbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengirimanbtnActionPerformed(evt);
            }
        });
        getContentPane().add(pengirimanbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, -1, -1));

        pelangganbtn.setText("Penerima");
        pelangganbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganbtnActionPerformed(evt);
            }
        });
        getContentPane().add(pelangganbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 91, -1));

        kurirbtn.setText("Kurir");
        kurirbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kurirbtnActionPerformed(evt);
            }
        });
        getContentPane().add(kurirbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 91, -1));

        barangbtn.setText("Barang");
        barangbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangbtnActionPerformed(evt);
            }
        });
        getContentPane().add(barangbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 90, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 92, 563, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 86));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("HALAMAN UTAMA N&B");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Daftar-Ekspedisi-COD.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pengirimanbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pengirimanbtnActionPerformed
        pengiriman pengirimanForm = new pengiriman();
        pengirimanForm.setVisible(true);
        this.dispose(); // close the current form
    }//GEN-LAST:event_pengirimanbtnActionPerformed

    private void pelangganbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganbtnActionPerformed
        penerima penerimaForm = new penerima();
        penerimaForm.setVisible(true);
        this.dispose(); // close the current form
    }//GEN-LAST:event_pelangganbtnActionPerformed

    private void barangbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangbtnActionPerformed
        barang barangForm = new barang();
        barangForm.setVisible(true);
        this.dispose(); // close the current form
    }//GEN-LAST:event_barangbtnActionPerformed

    private void kurirbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kurirbtnActionPerformed
        kurir kurirForm = new kurir();
        kurirForm.setVisible(true);
        this.dispose(); // close the current form
    }//GEN-LAST:event_kurirbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(halaman_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new halaman_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barangbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton kurirbtn;
    private javax.swing.JButton pelangganbtn;
    private javax.swing.JButton pengirimanbtn;
    // End of variables declaration//GEN-END:variables
}
