/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pengiriman_barang;

/**
 *
 * @author Tasya
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksidb;
import java.sql.*;

public class kurir extends javax.swing.JFrame {
    
    private Connection conn;
    private DefaultTableModel tableModel;
    public Statement st;
    public ResultSet rs;
    /**
     * Creates new form kurir
     */
    public kurir() {
        initComponents();
        conn = koneksidb.BukaKoneksi();
        tableModel = (DefaultTableModel) tablekurir.getModel();
        TampilData();
        
        // Tambahkan MouseListener ke tabel
        tablekurir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tablekurir.getSelectedRow();
                if(row != -1) {
                    kolom1.setText(tableModel.getValueAt(row, 0).toString());
                    kolom2.setText(tableModel.getValueAt(row, 1).toString());
                    kolom3.setText(tableModel.getValueAt(row, 2).toString());
                }
            }
        });
    }
    
    private void TampilData(){
        try{
            st = conn.createStatement();
            rs = st.executeQuery("SELECT*FROM kurir");
            
            tableModel.setRowCount(0); // Clear the table model
            
            while(rs.next()){
                Object[] data={
                rs.getString("Id_kurir"),
                rs.getString("Nama_kurir"),
                rs.getString("Jenis_kelamin"),
                };
                tableModel.addRow(data);
            }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablekurir = new javax.swing.JTable();
        buatbtn = new javax.swing.JButton();
        pbhrbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        kolom1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        kolom2 = new javax.swing.JTextField();
        caribtn = new javax.swing.JButton();
        pcrbox = new javax.swing.JComboBox<>();
        pencarian = new javax.swing.JTextField();
        kembalibtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        kolom3 = new javax.swing.JTextField();
        ulangbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("FORM KURIR");

        tablekurir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Kurir", "Nama Kurir", "Jenis Kelamin"
            }
        ));
        jScrollPane1.setViewportView(tablekurir);

        buatbtn.setText("Buat");
        buatbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buatbtnActionPerformed(evt);
            }
        });

        pbhrbtn.setText("Perbaharui");
        pbhrbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pbhrbtnActionPerformed(evt);
            }
        });

        hapusbtn.setText("Hapus");
        hapusbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("ID kurir");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nama kurir");

        caribtn.setText("Cari");
        caribtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caribtnActionPerformed(evt);
            }
        });

        pcrbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Kurir", "Nama Kurir", "Jenis Kelamin", " " }));
        pcrbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcrboxActionPerformed(evt);
            }
        });

        pencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencarianActionPerformed(evt);
            }
        });

        kembalibtn.setText("Kembali");
        kembalibtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalibtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Jenis Kelamin");

        ulangbtn.setText("Ulang");
        ulangbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulangbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(caribtn)
                        .addGap(18, 18, 18)
                        .addComponent(pcrbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(buatbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(pbhrbtn)
                                .addGap(50, 50, 50)
                                .addComponent(hapusbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(ulangbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kolom1)
                            .addComponent(kolom2)
                            .addComponent(kolom3, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(kembalibtn)
                        .addGap(26, 26, 26))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(kolom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kolom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buatbtn)
                    .addComponent(pbhrbtn)
                    .addComponent(hapusbtn)
                    .addComponent(ulangbtn))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caribtn)
                    .addComponent(pcrbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(kembalibtn)
                .addGap(18, 18, 18))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/360_F_262293274_BgGtnhf3gAZJkEt5vMj88oUK5Pwjguji.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buatbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buatbtnActionPerformed
        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Failed to connect to database!");
            return;
        }

        try {
            String ID = kolom1.getText();
            String nama = kolom2.getText();
            String jenis = kolom3.getText();

            String query = "INSERT INTO kurir (Id_kurir, Nama_kurir, Jenis_kelamin) VALUES (?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, ID);
            pstmt.setString(2, nama);
            pstmt.setString(3, jenis);

            pstmt.executeUpdate();

            TampilData(); // Refresh tabel setelah insert

            // Clear the input fields
            kolom1.setText("");
            kolom2.setText("");
            kolom3.setText("");

            JOptionPane.showMessageDialog(null, "Data berhasil disimpan!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_buatbtnActionPerformed

    private void pbhrbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pbhrbtnActionPerformed
        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Failed to connect to database!");
            return;
        }

        int row = tablekurir.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Pilih baris yang akan diperbarui!");
            return;
        }

        try {
            String ID = kolom1.getText();
            String nama = kolom2.getText();
            String jenis = kolom3.getText();

            String query = "UPDATE kurir SET Nama_kurir = ?, Jenis_kelamin = ? WHERE Id_kurir = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, nama);
            pstmt.setString(2, jenis);
            pstmt.setString(3, ID);
            pstmt.executeUpdate();

            TampilData(); // Refresh tabel setelah update

            JOptionPane.showMessageDialog(null, "Data berhasil diperbarui!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_pbhrbtnActionPerformed

    private void pencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencarianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pencarianActionPerformed

    private void kembalibtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalibtnActionPerformed
        halaman_utama halaman_utamaForm = new halaman_utama();
        halaman_utamaForm.setVisible(true);
        this.dispose(); // close the current form
    }//GEN-LAST:event_kembalibtnActionPerformed

    private void caribtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caribtnActionPerformed
        if (conn == null) {
        JOptionPane.showMessageDialog(null, "Failed to connect to database!");
        return;
    }

    String selectedOption = (String) pcrbox.getSelectedItem();
    String searchValue = pencarian.getText();

    String columnName = "";
    switch (selectedOption) {
        case "ID Kurir":
            columnName = "Id_kurir";
            break;
        case "Nama Kurir":
            columnName = "Nama_kurir";
            break;
        case "Jenis Kelamin":
            columnName = "Jenis_kelamin";
            break;
        default:
            JOptionPane.showMessageDialog(null, "Invalid option selected!");
            return;
    }

    try {
        String query = "SELECT * FROM kurir WHERE " + columnName + " LIKE ?";
        PreparedStatement pstmt = conn.prepareStatement(query);
        pstmt.setString(1, "%" + searchValue + "%");
        ResultSet rs = pstmt.executeQuery();

        tableModel.setRowCount(0); // Clear the table model

        if (rs.next()) { // Check if rs has any rows
            do {
                Object[] data = {
                    rs.getString("Id_kurir"),
                    rs.getString("Nama_kurir"),
                    rs.getString("Jenis_kelamin")
                };
                tableModel.addRow(data);
            } while (rs.next()); // Use do-while loop to iterate over rs

            JOptionPane.showMessageDialog(null, "Data berhasil dicari!");
        } else {
            JOptionPane.showMessageDialog(null, "Data tidak ditemukan!");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
    }//GEN-LAST:event_caribtnActionPerformed

    private void hapusbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusbtnActionPerformed
        if (conn == null) {
            JOptionPane.showMessageDialog(null, "Failed to connect to database!");
            return;
        }

        int row = tablekurir.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(null, "Select a row to delete!");
            return;
        }

        String ID = (String) tableModel.getValueAt(row, 0);
        String nama = (String) tableModel.getValueAt(row, 1);
        String jenis = (String) tableModel.getValueAt(row, 2);

        try {
            String query = "DELETE FROM kurir WHERE Id_kurir = ? AND Nama_kurir = ? AND Jenis_kelamin = ?";
            PreparedStatement pstmt = conn.prepareStatement(query);
            pstmt.setString(1, ID);
            pstmt.setString(2, nama);
            pstmt.setString(3, jenis);
            pstmt.executeUpdate();

            tableModel.removeRow(row);

            TampilData(); // Call TampilData() to refresh the table

            JOptionPane.showMessageDialog(null, "Data berhasil dihapus!");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_hapusbtnActionPerformed

    private void pcrboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcrboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcrboxActionPerformed

    private void ulangbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulangbtnActionPerformed
        kolom1.setText("");
        kolom2.setText("");
        kolom3.setText("");
    }//GEN-LAST:event_ulangbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kurir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kurir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buatbtn;
    private javax.swing.JButton caribtn;
    private javax.swing.JButton hapusbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembalibtn;
    private javax.swing.JTextField kolom1;
    private javax.swing.JTextField kolom2;
    private javax.swing.JTextField kolom3;
    private javax.swing.JButton pbhrbtn;
    private javax.swing.JComboBox<String> pcrbox;
    private javax.swing.JTextField pencarian;
    private javax.swing.JTable tablekurir;
    private javax.swing.JButton ulangbtn;
    // End of variables declaration//GEN-END:variables
}
